Merge PR #297, #306, #307 and #310 into main (#309)
* Add smart-contract search entry point (#287)

* Add playgrounds (#288)

* Bump axios from 0.21.1 to 0.21.4 (#285)

Bumps [axios](https://github.com/axios/axios) from 0.21.1 to 0.21.4.
- [Release notes](https://github.com/axios/axios/releases)
- [Changelog](https://github.com/axios/axios/blob/master/CHANGELOG.md)
- [Commits](https://github.com/axios/axios/compare/v0.21.1...v0.21.4)

---
updated-dependencies:
- dependency-name: axios
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Fixes Cardano Explorer and Pull Request Template links (#272)

* changes the default language of a link's site to English

* fixes link to pull request template in contributing document

Co-authored-by: Tommy

* Adding alonzo genesis files (#291)

* Adding alonzo genesis files

* Update running-cardano.md

* fix typo (#305)

* fix typo

* september spotlight interview

Co-authored-by: Kevin Cislak 

* Removing the random constraint for building wallet (#297)

Building the wallet with `--constraint="random<1.2"` results in:

```
Building library for cardano-wallet-core-2021.9.9..
[59 of 95] Compiling Cardano.Wallet.DB.Sqlite.Types ( src/Cardano/Wallet/DB/Sqlite/Types.hs, /home/cardano/cardano-src/cardano-wallet/dist-newstyle/build/x86_64-linux/ghc-8.10.7/cardano-wallet-core-2021.9.9/build/Cardano/Wallet/DB/Sqlite/Types.o, /home/cardano/cardano-src/cardano-wallet/dist-newstyle/build/x86_64-linux/ghc-8.10.7/cardano-wallet-core-2021.9.9/build/Cardano/Wallet/DB/Sqlite/Types.dyn_o )

src/Cardano/Wallet/DB/Sqlite/Types.hs:122:1: error:
    Could not load module ‘System.Random.Internal’
    It is a member of the hidden package ‘random-1.2.0’.
    Perhaps you need to add ‘random’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
    |
122 | import System.Random.Internal
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Failed to build cardano-wallet-core-2021.9.9 (which is required by
exe:local-cluster from cardano-wallet-2021.9.9, test:integration from
cardano-wallet-2021.9.9 and others).
```

Issue here: https://github.com/input-output-hk/cardano-wallet/issues/2824
Raising this PR to discuss as I don't understand the significance of removing the constraint.

Versions:
* cardano-wallet tag v2021-09-09
* cabal-install version 3.4.0.0
* compiled using version 3.4.0.0 of the Cabal library
* The Glorious Glasgow Haskell Compilation System, version 8.10.7
* Ubuntu 20.04.3 LTS

* september spotlight article (#306)

Co-authored-by: Kevin Cislak

* Update creating-wallet-faucet.md (#307)

* Update creating-wallet-faucet.md

* Update creating-wallet-faucet.md

* Delete duplicate article (#310)

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Rodrigo Matos 
Co-authored-by: John Imison 
Co-authored-by: cislakk 
Co-authored-by: Kevin Cislak
Co-authored-by: Javier La Banca